<?php
function getTranslations($lang) {
    $translations = [
        'ru' => [
            'title' => 'SEO Анализатор', 'version' => 'Версия 1.8', 'slogan' => 'Мощный бесплатный инструмент для анализа и улучшения SEO вашего сайта',
            'h2' => 'Анализ SEO-параметров', 'placeholder' => 'example.com', 'button' => 'Анализировать',
            'error' => 'Ошибка: Не удалось загрузить страницу. Проверьте URL и интернет-соединение.',
            'http_status' => 'HTTP Статус: ', 'https_check' => 'HTTPS: ', 'url_structure' => 'Структура URL: ', 'links_check' => 'Ссылки: ',
            'social_meta' => 'Open Graph (соцсети): ', 'title_check' => 'Title: ', 'meta_desc' => 'Meta Description: ',
            'meta_keywords' => 'Meta Keywords: ', 'meta_robots' => 'Meta Robots: ', 'h1_check' => 'H1: ', 'h2_check' => 'H2: ',
            'images_alt' => 'Alt у изображений: ', 'viewport' => 'Viewport: ', 'load_time' => 'Время загрузки: ', 'content_size' => 'Размер контента: ',
            'optimal' => 'Отлично', 'too_long' => 'Слишком длинный', 'absent' => 'Отсутствует', 'present' => 'Есть', 'too_many' => 'Слишком много',
            'all_with_alt' => 'Все с alt', 'without_alt' => 'без alt', 'good' => 'Хорошо', 'slow' => 'Медленно', 'enough' => 'Достаточно',
            'low_content' => 'Мало контента', 'noindex' => 'Индексация запрещена', 'not_set' => 'Не указан (индексация разрешена)',
            'configured' => 'Настроен', 'secure' => 'Безопасно', 'insecure' => 'Не защищено', 'readable' => 'Читаемый',
            'complex' => 'Сложный / длинный', 'internal' => 'Внутренние: ', 'external' => 'Внешние: ', 'nofollow' => 'Nofollow: ',
            'symbols' => 'симв.', 'help' => 'Справка', 'about' => 'О программе',
            'about_text' => '<strong>SEO Анализатор 1.8</strong> — современный инструмент для быстрого анализа + заказ полного аудита.',
            'features' => 'Возможности:', 'features_list' => '<li>Проверка Title, Description, H1/H2</li><li>Анализ alt у изображений</li><li>Скорость и размер контента</li><li>Структура URL и ссылки</li><li>Open Graph</li><li>8 языков</li><li>Лента недавних анализов</li><li>Заказ полного аудита</li>',
            'howto' => 'Как пользоваться:', 'howto_list' => '<li>Выберите протокол</li><li>Введите домен</li><li>Нажмите «Анализировать»</li>',
            'tips' => 'Советы по SEO-оптимизации (15 полезных):',
            'tips_list' => '<li><i class="fas fa-heading"></i> <strong>Title</strong> — 50–60 символов.</li><li><i class="fas fa-align-left"></i> <strong>Meta Description</strong> — 120–160 символов с ключевыми словами.</li><li><i class="fas fa-font"></i> <strong>H1</strong> — только один на странице.</li><li><i class="fas fa-image"></i> <strong>Alt у изображений</strong> — обязательно для всех картинок.</li><li><i class="fas fa-mobile-alt"></i> <strong>Viewport</strong> — обязателен для мобильной версии.</li><li><i class="fas fa-clock"></i> <strong>Скорость загрузки</strong> — цельтесь меньше 3 секунд.</li><li><i class="fas fa-file-alt"></i> <strong>Контент</strong> — минимум 50 KB текста.</li><li><i class="fas fa-link"></i> <strong>URL</strong> — короткий, читаемый, с ключевыми словами.</li><li><i class="fas fa-exchange-alt"></i> <strong>Внутренняя перелинковка</strong> — распределяйте ссылочный вес.</li><li><i class="fas fa-code"></i> <strong>Schema.org (JSON-LD)</strong> — богатые сниппеты.</li><li><i class="fas fa-link"></i> <strong>Canonical</strong> — избегайте дублей.</li><li><i class="fas fa-tachometer-alt"></i> <strong>Core Web Vitals</strong> — LCP < 2.5 с, FID < 100 мс, CLS < 0.1.</li><li><i class="fas fa-file-signature"></i> <strong>Уникальный контент</strong> — никогда не копируйте.</li><li><i class="fas fa-map"></i> <strong>Sitemap.xml</strong> — отправьте в Google и Яндекс.</li><li><i class="fas fa-key"></i> <strong>Ключевые слова</strong> — естественное размещение в первом абзаце.</li>',
            'history' => 'Недавние анализы', 'scanning' => 'Анализируем сайт:',
            'order_audit' => 'Заказать полный аудит сайта', 'donate_title' => 'Поддержать проект',
            'recommendations' => 'Что нужно исправить:',
            'rec_title_too_long' => 'Сократите Title до 60 символов.', 'rec_title_absent' => 'Добавьте тег Title.',
            'rec_meta_desc_too_long' => 'Сократите Description до 160 символов.', 'rec_meta_desc_absent' => 'Добавьте Meta Description.',
            'rec_h1_absent' => 'Добавьте один H1.', 'rec_h1_too_many' => 'Оставьте только один H1.',
            'rec_images_alt' => 'Добавьте alt к изображениям: ', 'rec_viewport_absent' => 'Добавьте viewport.',
            'rec_load_time_slow' => 'Ускорьте загрузку до < 3 секунд.', 'rec_content_low' => 'Увеличьте объём текста минимум до 50 KB.',
            'rec_https_insecure' => 'Перейдите на HTTPS.', 'rec_url_complex' => 'Сделайте URL короче и читаемее.',
            'rec_social_meta_absent' => 'Добавьте og:title и og:description.',
            'sec' => 'сек.', 'no_history' => 'Пока нет анализов',
            'name_label' => 'Ваше имя', 'email_label' => 'Email', 'site_label' => 'URL сайта',
            'message_label' => 'Что именно нужно проанализировать', 'submit_audit' => 'Отправить заявку',
            'audit_success' => 'Заявка успешно отправлена! Мы свяжемся с вами в ближайшее время.',
            'donate_text' => 'Если инструмент помог — поддержите разработчика ☕',
            'coffee_button' => 'Купить мне кофе на BuyMeACoffee',
            'write_dev' => 'Написать разработчику',
            'popularity' => 'Популярность поисковых запросов',
            'queries_count' => 'Количество запросов: ',
            'top_10_queries' => 'Топ-10 популярных запросов:',
            'privacy_title' => 'Политика конфиденциальности',
            'privacy_text' => 'Мы используем cookies и собираем только необходимые данные (email для подписки, имя и email для заказа аудита). Ваши данные не передаются третьим лицам.',
            'accept' => 'Принять и продолжить',
            'reject' => 'Отклонить',
            'reject_message' => 'Вы отказались от согласия. Некоторые функции могут быть недоступны.'
        ],
        'en' => [
            'title' => 'SEO Analyzer', 'version' => 'Version 1.8', 'slogan' => 'Powerful free tool to analyze and improve your website SEO',
            'h2' => 'SEO Parameters Analysis', 'placeholder' => 'example.com', 'button' => 'Analyze',
            'error' => 'Error: Failed to load the page. Check URL and internet connection.',
            'http_status' => 'HTTP Status: ', 'https_check' => 'HTTPS: ', 'url_structure' => 'URL Structure: ', 'links_check' => 'Links: ',
            'social_meta' => 'Open Graph (social): ', 'title_check' => 'Title: ', 'meta_desc' => 'Meta Description: ',
            'meta_keywords' => 'Meta Keywords: ', 'meta_robots' => 'Meta Robots: ', 'h1_check' => 'H1: ', 'h2_check' => 'H2: ',
            'images_alt' => 'Image alt: ', 'viewport' => 'Viewport: ', 'load_time' => 'Load time: ', 'content_size' => 'Content size: ',
            'optimal' => 'Excellent', 'too_long' => 'Too long', 'absent' => 'Absent', 'present' => 'Present', 'too_many' => 'Too many',
            'all_with_alt' => 'All with alt', 'without_alt' => 'without alt', 'good' => 'Good', 'slow' => 'Slow', 'enough' => 'Enough',
            'low_content' => 'Low content', 'noindex' => 'Indexing forbidden', 'not_set' => 'Not set (indexing allowed)',
            'configured' => 'Configured', 'secure' => 'Secure', 'insecure' => 'Insecure', 'readable' => 'Readable',
            'complex' => 'Complex / long', 'internal' => 'Internal: ', 'external' => 'External: ', 'nofollow' => 'Nofollow: ',
            'symbols' => 'chars', 'help' => 'Help', 'about' => 'About',
            'about_text' => '<strong>SEO Analyzer 1.8</strong> — modern tool for quick analysis + full audit order.',
            'features' => 'Features:', 'features_list' => '<li>Title, Description, H1/H2 check</li><li>Image alt analysis</li><li>Speed & content size</li><li>URL structure & links</li><li>Open Graph</li><li>8 languages</li><li>Recent analyses feed</li><li>Order full audit</li>',
            'howto' => 'How to use:', 'howto_list' => '<li>Choose protocol</li><li>Enter domain</li><li>Click "Analyze"</li>',
            'tips' => 'SEO Optimization Tips (15 useful):',
            'tips_list' => '<li><i class="fas fa-heading"></i> <strong>Title</strong> — 50–60 characters.</li><li><i class="fas fa-align-left"></i> <strong>Meta Description</strong> — 120–160 characters with keywords.</li><li><i class="fas fa-font"></i> <strong>H1</strong> — only one per page.</li><li><i class="fas fa-image"></i> <strong>Image alt</strong> — mandatory for all images.</li><li><i class="fas fa-mobile-alt"></i> <strong>Viewport</strong> — required for mobile.</li><li><i class="fas fa-clock"></i> <strong>Load time</strong> — under 3 seconds.</li><li><i class="fas fa-file-alt"></i> <strong>Content</strong> — at least 50 KB text.</li><li><i class="fas fa-link"></i> <strong>URL</strong> — short, readable, keyword-rich.</li><li><i class="fas fa-exchange-alt"></i> <strong>Internal linking</strong> — distribute link equity.</li><li><i class="fas fa-code"></i> <strong>Schema.org</strong> — rich snippets.</li><li><i class="fas fa-link"></i> <strong>Canonical</strong> — avoid duplicates.</li><li><i class="fas fa-tachometer-alt"></i> <strong>Core Web Vitals</strong> — LCP < 2.5s, FID < 100ms, CLS < 0.1.</li><li><i class="fas fa-file-signature"></i> <strong>Unique content</strong> — never copy.</li><li><i class="fas fa-map"></i> <strong>Sitemap.xml</strong> — submit to Google & Bing.</li><li><i class="fas fa-key"></i> <strong>Keywords</strong> — natural placement in first paragraph.</li>',
            'history' => 'Recent Analyses', 'scanning' => 'Scanning website:',
            'order_audit' => 'Order Full SEO Audit', 'donate_title' => 'Support the Project',
            'recommendations' => 'What to fix:',
            'rec_title_too_long' => 'Shorten Title to 60 characters.', 'rec_title_absent' => 'Add Title tag.',
            'rec_meta_desc_too_long' => 'Shorten Description to 160 characters.', 'rec_meta_desc_absent' => 'Add Meta Description.',
            'rec_h1_absent' => 'Add one H1.', 'rec_h1_too_many' => 'Leave only one H1.',
            'rec_images_alt' => 'Add alt to images: ', 'rec_viewport_absent' => 'Add viewport tag.',
            'rec_load_time_slow' => 'Speed up loading to < 3 seconds.', 'rec_content_low' => 'Increase text volume to at least 50 KB.',
            'rec_https_insecure' => 'Switch to HTTPS.', 'rec_url_complex' => 'Make URL shorter and readable.',
            'rec_social_meta_absent' => 'Add og:title and og:description.',
            'sec' => 'sec.', 'no_history' => 'No analyses yet',
            'name_label' => 'Your name', 'email_label' => 'Email', 'site_label' => 'Site URL',
            'message_label' => 'What needs to be analyzed', 'submit_audit' => 'Submit request',
            'audit_success' => 'Request successfully sent! We will contact you shortly.',
            'donate_text' => 'If the tool helped — support the developer ☕',
            'coffee_button' => 'Buy me a coffee on BuyMeACoffee',
            'write_dev' => 'Write to developer',
            'popularity' => 'Search query popularity',
            'queries_count' => 'Number of queries: ',
            'top_10_queries' => 'Top 10 popular queries:'
        ],
        'de' => [
            'title' => 'SEO-Analysator', 'version' => 'Version 1.8', 'slogan' => 'Leistungsstarkes kostenloses Tool zur Analyse und Verbesserung des SEO Ihrer Website',
            'h2' => 'SEO-Parameter-Analyse', 'placeholder' => 'example.com', 'button' => 'Analysieren',
            'error' => 'Fehler: Seite konnte nicht geladen werden. Überprüfen Sie die URL und die Internetverbindung.',
            'http_status' => 'HTTP-Status: ', 'https_check' => 'HTTPS: ', 'url_structure' => 'URL-Struktur: ', 'links_check' => 'Links: ',
            'social_meta' => 'Open Graph (Social Media): ', 'title_check' => 'Title: ', 'meta_desc' => 'Meta Description: ',
            'meta_keywords' => 'Meta Keywords: ', 'meta_robots' => 'Meta Robots: ', 'h1_check' => 'H1: ', 'h2_check' => 'H2: ',
            'images_alt' => 'Alt bei Bildern: ', 'viewport' => 'Viewport: ', 'load_time' => 'Ladezeit: ', 'content_size' => 'Inhaltsgröße: ',
            'optimal' => 'Exzellent', 'too_long' => 'Zu lang', 'absent' => 'Fehlt', 'present' => 'Vorhanden', 'too_many' => 'Zu viele',
            'all_with_alt' => 'Alle mit alt', 'without_alt' => 'ohne alt', 'good' => 'Gut', 'slow' => 'Langsam', 'enough' => 'Ausreichend',
            'low_content' => 'Wenig Inhalt', 'noindex' => 'Indexierung verboten', 'not_set' => 'Nicht gesetzt (Indexierung erlaubt)',
            'configured' => 'Konfiguriert', 'secure' => 'Sicher', 'insecure' => 'Unsicher', 'readable' => 'Lesbar',
            'complex' => 'Komplex / lang', 'internal' => 'Interne: ', 'external' => 'Externe: ', 'nofollow' => 'Nofollow: ',
            'symbols' => 'Zeichen', 'help' => 'Hilfe', 'about' => 'Über das Programm',
            'about_text' => '<strong>SEO-Analysator 1.8</strong> — modernes Tool zur schnellen Analyse + Bestellung eines vollständigen Audits.',
            'features' => 'Funktionen:', 'features_list' => '<li>Prüfung Title, Description, H1/H2</li><li>Alt-Tag-Analyse</li><li>Ladezeit & Inhaltsgröße</li><li>URL & Links</li><li>Open Graph</li><li>8 Sprachen</li><li>Letzte Analysen</li><li>Vollständigen Audit bestellen</li>',
            'howto' => 'So verwenden:', 'howto_list' => '<li>Protokoll wählen</li><li>Domain eingeben</li><li>„Analysieren“ klicken</li>',
            'tips' => 'SEO-Optimierungstipps (15 nützliche):',
            'tips_list' => '<li><i class="fas fa-heading"></i> <strong>Title</strong> — 50–60 Zeichen halten.</li><li><i class="fas fa-align-left"></i> <strong>Meta Description</strong> — 120–160 Zeichen mit Keywords.</li><li><i class="fas fa-font"></i> <strong>H1</strong> — nur einer pro Seite.</li><li><i class="fas fa-image"></i> <strong>Alt bei Bildern</strong> — für alle Bilder Pflicht.</li><li><i class="fas fa-mobile-alt"></i> <strong>Viewport</strong> — für mobile Ansicht erforderlich.</li><li><i class="fas fa-clock"></i> <strong>Ladezeit</strong> — unter 3 Sekunden anstreben.</li><li><i class="fas fa-file-alt"></i> <strong>Inhalt</strong> — mindestens 50 KB Text.</li><li><i class="fas fa-link"></i> <strong>URL</strong> — kurz, lesbar, mit Keywords.</li><li><i class="fas fa-exchange-alt"></i> <strong>Interne Verlinkung</strong> — Linkjuice verteilen.</li><li><i class="fas fa-code"></i> <strong>Schema.org</strong> — Rich Snippets.</li><li><i class="fas fa-link"></i> <strong>Canonical</strong> — Duplikate vermeiden.</li><li><i class="fas fa-tachometer-alt"></i> <strong>Core Web Vitals</strong> — LCP < 2.5 s, FID < 100 ms, CLS < 0.1.</li><li><i class="fas fa-file-signature"></i> <strong>Einzigartiger Inhalt</strong> — niemals kopieren.</li><li><i class="fas fa-map"></i> <strong>Sitemap.xml</strong> — an Google und Bing senden.</li><li><i class="fas fa-key"></i> <strong>Keywords</strong> — natürlich im ersten Absatz platzieren.</li>',
            'history' => 'Letzte Analysen', 'scanning' => 'Analysiere Website:',
            'order_audit' => 'Vollständigen Audit bestellen', 'donate_title' => 'Projekt unterstützen',
            'recommendations' => 'Was zu beheben ist:',
            'rec_title_too_long' => 'Title auf 60 Zeichen kürzen.', 'rec_title_absent' => 'Title-Tag hinzufügen.',
            'rec_meta_desc_too_long' => 'Description auf 160 Zeichen kürzen.', 'rec_meta_desc_absent' => 'Meta Description hinzufügen.',
            'rec_h1_absent' => 'Einen H1 hinzufügen.', 'rec_h1_too_many' => 'Nur einen H1 behalten.',
            'rec_images_alt' => 'Alt-Tags zu Bildern hinzufügen: ', 'rec_viewport_absent' => 'Viewport-Tag hinzufügen.',
            'rec_load_time_slow' => 'Ladezeit unter 3 Sekunden bringen.', 'rec_content_low' => 'Textmenge auf mind. 50 KB erhöhen.',
            'rec_https_insecure' => 'Auf HTTPS umstellen.', 'rec_url_complex' => 'URL kürzer und lesbarer machen.',
            'rec_social_meta_absent' => 'og:title und og:description hinzufügen.',
            'sec' => 'Sek.', 'no_history' => 'Noch keine Analysen',
            'name_label' => 'Ihr Name', 'email_label' => 'E-Mail', 'site_label' => 'Website-URL',
            'message_label' => 'Was genau analysiert werden soll', 'submit_audit' => 'Anfrage senden',
            'audit_success' => 'Anfrage erfolgreich gesendet! Wir melden uns in Kürze.',
            'donate_text' => 'Wenn das Tool geholfen hat — unterstützen Sie den Entwickler ☕',
            'coffee_button' => 'Kaufen Sie mir einen Kaffee auf BuyMeACoffee',
            'write_dev' => 'Schreiben Sie dem Entwickler',
            'popularity' => 'Beliebtheit der Suchanfragen',
            'queries_count' => 'Anzahl der Anfragen: ',
            'top_10_queries' => 'Top-10 beliebte Anfragen:'
        ],
        'ua' => [
            'title' => 'SEO Аналізатор', 'version' => 'Версія 1.8', 'slogan' => 'Потужний безкоштовний інструмент для аналізу та покращення SEO вашого сайту',
            'h2' => 'Аналіз SEO-параметрів', 'placeholder' => 'example.com', 'button' => 'Аналізувати',
            'error' => 'Помилка: Не вдалося завантажити сторінку. Перевірте URL та інтернет-з’єднання.',
            'http_status' => 'HTTP Статус: ', 'https_check' => 'HTTPS: ', 'url_structure' => 'Структура URL: ', 'links_check' => 'Посилання: ',
            'social_meta' => 'Open Graph (соцмережі): ', 'title_check' => 'Title: ', 'meta_desc' => 'Meta Description: ',
            'meta_keywords' => 'Meta Keywords: ', 'meta_robots' => 'Meta Robots: ', 'h1_check' => 'H1: ', 'h2_check' => 'H2: ',
            'images_alt' => 'Alt у зображень: ', 'viewport' => 'Viewport: ', 'load_time' => 'Час завантаження: ', 'content_size' => 'Розмір контенту: ',
            'optimal' => 'Відмінно', 'too_long' => 'Занадто довгий', 'absent' => 'Відсутній', 'present' => 'Є', 'too_many' => 'Занадто багато',
            'all_with_alt' => 'Усі з alt', 'without_alt' => 'без alt', 'good' => 'Добре', 'slow' => 'Повільно', 'enough' => 'Достатньо',
            'low_content' => 'Мало контенту', 'noindex' => 'Індексація заборонена', 'not_set' => 'Не вказано (індексація дозволена)',
            'configured' => 'Налаштовано', 'secure' => 'Безпечний', 'insecure' => 'Не захищений', 'readable' => 'Читабельний',
            'complex' => 'Складний / довгий', 'internal' => 'Внутрішні: ', 'external' => 'Зовнішні: ', 'nofollow' => 'Nofollow: ',
            'symbols' => 'симв.', 'help' => 'Довідка', 'about' => 'Про програму',
            'about_text' => '<strong>SEO Аналізатор 1.8</strong> — сучасний інструмент для швидкого аналізу + замовлення повного аудиту.',
            'features' => 'Можливості:', 'features_list' => '<li>Перевірка Title, Description, H1/H2</li><li>Аналіз alt у зображень</li><li>Швидкість та розмір контенту</li><li>Структура URL та посилання</li><li>Open Graph</li><li>8 мов</li><li>Стрічка останніх аналізів</li><li>Замовлення повного аудиту</li>',
            'howto' => 'Як користуватися:', 'howto_list' => '<li>Оберіть протокол</li><li>Введіть домен</li><li>Натисніть «Аналізувати»</li>',
            'tips' => 'Поради з SEO-оптимізації (15 корисних):',
            'tips_list' => '<li><i class="fas fa-heading"></i> <strong>Title</strong> — 50–60 символів.</li><li><i class="fas fa-align-left"></i> <strong>Meta Description</strong> — 120–160 символів з ключовими словами.</li><li><i class="fas fa-font"></i> <strong>H1</strong> — тільки один на сторінці.</li><li><i class="fas fa-image"></i> <strong>Alt у зображень</strong> — обов’язково для всіх картинок.</li><li><i class="fas fa-mobile-alt"></i> <strong>Viewport</strong> — обов’язковий для мобільної версії.</li><li><i class="fas fa-clock"></i> <strong>Швидкість завантаження</strong> — цільтеся менше 3 секунд.</li><li><i class="fas fa-file-alt"></i> <strong>Контент</strong> — мінімум 50 KB тексту.</li><li><i class="fas fa-link"></i> <strong>URL</strong> — короткий, читабельний, з ключовими словами.</li><li><i class="fas fa-exchange-alt"></i> <strong>Внутрішня перелінковка</strong> — розподіляйте посилальний вага.</li><li><i class="fas fa-code"></i> <strong>Schema.org (JSON-LD)</strong> — багаті сніппети.</li><li><i class="fas fa-link"></i> <strong>Canonical</strong> — уникайте дублів.</li><li><i class="fas fa-tachometer-alt"></i> <strong>Core Web Vitals</strong> — LCP < 2.5 с, FID < 100 мс, CLS < 0.1.</li><li><i class="fas fa-file-signature"></i> <strong>Унікальний контент</strong> — ніколи не копіюйте.</li><li><i class="fas fa-map"></i> <strong>Sitemap.xml</strong> — відправте в Google та Яндекс.</li><li><i class="fas fa-key"></i> <strong>Ключові слова</strong> — природне розміщення в першому абзаці.</li>',
            'history' => 'Останні аналізи', 'scanning' => 'Аналізуємо сайт:',
            'order_audit' => 'Замовити повний аудит сайту', 'donate_title' => 'Підтримати проект',
            'recommendations' => 'Що потрібно виправити:',
            'rec_title_too_long' => 'Скоротіть Title до 60 символів.', 'rec_title_absent' => 'Додайте тег Title.',
            'rec_meta_desc_too_long' => 'Скоротіть Description до 160 символів.', 'rec_meta_desc_absent' => 'Додайте Meta Description.',
            'rec_h1_absent' => 'Додайте один H1.', 'rec_h1_too_many' => 'Залиште тільки один H1.',
            'rec_images_alt' => 'Додайте alt до зображень: ', 'rec_viewport_absent' => 'Додайте viewport.',
            'rec_load_time_slow' => 'Прискорте завантаження до < 3 секунд.', 'rec_content_low' => 'Збільште об’єм тексту мінімум до 50 KB.',
            'rec_https_insecure' => 'Перейдіть на HTTPS.', 'rec_url_complex' => 'Зробіть URL коротшим і читабельнішим.',
            'rec_social_meta_absent' => 'Додайте og:title та og:description.',
            'sec' => 'сек.', 'no_history' => 'Поки немає аналізів',
            'name_label' => 'Ваше ім’я', 'email_label' => 'Email', 'site_label' => 'URL сайту',
            'message_label' => 'Що саме потрібно проаналізувати', 'submit_audit' => 'Відправити заявку',
            'audit_success' => 'Заявка успішно відправлена! Ми зв’яжемося з вами найближчим часом.',
            'donate_text' => 'Якщо інструмент допоміг — підтримайте розробника ☕',
            'coffee_button' => 'Купити мені каву на BuyMeACoffee',
            'write_dev' => 'Написати розробнику',
            'popularity' => 'Популярність пошукових запитів',
            'queries_count' => 'Кількість запитів: ',
            'top_10_queries' => 'Топ-10 популярних запитів:'
        ],
        'lt' => [
            'title' => 'SEO Analizatorius', 'version' => 'Versija 1.8', 'slogan' => 'Galingas nemokamas įrankis jūsų svetainės SEO analizei ir gerinimui',
            'h2' => 'SEO parametrų analizė', 'placeholder' => 'example.com', 'button' => 'Analizuoti',
            'error' => 'Klaida: Nepavyko įkelti puslapio. Patikrinkite URL ir interneto ryšį.',
            'http_status' => 'HTTP Statusas: ', 'https_check' => 'HTTPS: ', 'url_structure' => 'URL struktūra: ', 'links_check' => 'Nuorodos: ',
            'social_meta' => 'Open Graph (socialiniai tinklai): ', 'title_check' => 'Title: ', 'meta_desc' => 'Meta Description: ',
            'meta_keywords' => 'Meta Keywords: ', 'meta_robots' => 'Meta Robots: ', 'h1_check' => 'H1: ', 'h2_check' => 'H2: ',
            'images_alt' => 'Alt prie paveikslėlių: ', 'viewport' => 'Viewport: ', 'load_time' => 'Įkrovimo laikas: ', 'content_size' => 'Turinio dydis: ',
            'optimal' => 'Puiku', 'too_long' => 'Per ilgas', 'absent' => 'Nėra', 'present' => 'Yra', 'too_many' => 'Per daug',
            'all_with_alt' => 'Visi su alt', 'without_alt' => 'be alt', 'good' => 'Gerai', 'slow' => 'Lėtai', 'enough' => 'Pakankamai',
            'low_content' => 'Mažai turinio', 'noindex' => 'Indeksavimas uždraustas', 'not_set' => 'Nenustatyta (indeksavimas leidžiamas)',
            'configured' => 'Nustatyta', 'secure' => 'Saugu', 'insecure' => 'Nesaugu', 'readable' => 'Skaitytina',
            'complex' => 'Sudėtinga / ilga', 'internal' => 'Vidinės: ', 'external' => 'Išorinės: ', 'nofollow' => 'Nofollow: ',
            'symbols' => 'simb.', 'help' => 'Pagalba', 'about' => 'Apie programą',
            'about_text' => '<strong>SEO Analizatorius 1.8</strong> — modernus įrankis greitai analizei + pilno audito užsakymui.',
            'features' => 'Galimybės:', 'features_list' => '<li>Title, Description, H1/H2 patikra</li><li>Alt žymių analizė</li><li>Įkrovimo greitis ir turinio dydis</li><li>URL struktūra ir nuorodos</li><li>Open Graph</li><li>8 kalbos</li><li>Paskutinių analizių juosta</li><li>Pilno audito užsakymas</li>',
            'howto' => 'Kaip naudotis:', 'howto_list' => '<li>Pasirinkite protokolą</li><li>Įveskite domeną</li><li>Spauskite „Analizuoti“</li>',
            'tips' => 'SEO optimizavimo patarimai (15 naudingų):',
            'tips_list' => '<li><i class="fas fa-heading"></i> <strong>Title</strong> — 50–60 simbolių.</li><li><i class="fas fa-align-left"></i> <strong>Meta Description</strong> — 120–160 simbolių su raktažodžiais.</li><li><i class="fas fa-font"></i> <strong>H1</strong> — tik vienas puslapyje.</li><li><i class="fas fa-image"></i> <strong>Alt prie paveikslėlių</strong> — privaloma visiems.</li><li><i class="fas fa-mobile-alt"></i> <strong>Viewport</strong> — privalomas mobiliems.</li><li><i class="fas fa-clock"></i> <strong>Įkrovimo greitis</strong> — siekite mažiau nei 3 sekundes.</li><li><i class="fas fa-file-alt"></i> <strong>Turinys</strong> — mažiausiai 50 KB teksto.</li><li><i class="fas fa-link"></i> <strong>URL</strong> — trumpas, skaitomas, su raktažodžiais.</li><li><i class="fas fa-exchange-alt"></i> <strong>Vidinės nuorodos</strong> — paskirstykite svorį.</li><li><i class="fas fa-code"></i> <strong>Schema.org</strong> — turtingi snippetai.</li><li><i class="fas fa-link"></i> <strong>Canonical</strong> — venkite dublikatų.</li><li><i class="fas fa-tachometer-alt"></i> <strong>Core Web Vitals</strong> — LCP < 2.5 s, FID < 100 ms, CLS < 0.1.</li><li><i class="fas fa-file-signature"></i> <strong>Unikalus turinys</strong> — niekada nekopijuokite.</li><li><i class="fas fa-map"></i> <strong>Sitemap.xml</strong> — siųskite į Google ir Bing.</li><li><i class="fas fa-key"></i> <strong>Raktažodžiai</strong> — natūraliai pirmame pastraipoje.</li>',
            'history' => 'Paskutinės analizės', 'scanning' => 'Analizuojame svetainę:',
            'order_audit' => 'Užsakyti pilną auditą', 'donate_title' => 'Paremti projektą',
            'recommendations' => 'Ką reikia pataisyti:',
            'rec_title_too_long' => 'Sutrumpinkite Title iki 60 simbolių.', 'rec_title_absent' => 'Pridėkite Title žymę.',
            'rec_meta_desc_too_long' => 'Sutrumpinkite Description iki 160 simbolių.', 'rec_meta_desc_absent' => 'Pridėkite Meta Description.',
            'rec_h1_absent' => 'Pridėkite vieną H1.', 'rec_h1_too_many' => 'Palikite tik vieną H1.',
            'rec_images_alt' => 'Pridėkite alt prie paveikslėlių: ', 'rec_viewport_absent' => 'Pridėkite viewport.',
            'rec_load_time_slow' => 'Pagreitinkite įkrovimą iki < 3 sekundžių.', 'rec_content_low' => 'Padidinkite teksto kiekį iki mažiausiai 50 KB.',
            'rec_https_insecure' => 'Pereikite į HTTPS.', 'rec_url_complex' => 'Padarykite URL trumpesnį ir skaitomesnį.',
            'rec_social_meta_absent' => 'Pridėkite og:title ir og:description.',
            'sec' => 'sek.', 'no_history' => 'Kol kas nėra analizės',
            'name_label' => 'Jūsų vardas', 'email_label' => 'El. paštas', 'site_label' => 'Svetainės URL',
            'message_label' => 'Ką tiksliai reikia analizuoti', 'submit_audit' => 'Siųsti užklausą',
            'audit_success' => 'Užklausa sėkmingai išsiųsta! Susisieksime su jumis netrukus.',
            'donate_text' => 'Jei įrankis padėjo — paremkite kūrėją ☕',
            'coffee_button' => 'Nupirkti man kavos per BuyMeACoffee',
            'write_dev' => 'Parašyti kūrėjui',
            'popularity' => 'Paieškos užklausų populiarumas',
            'queries_count' => 'Užklausų skaičius: ',
            'top_10_queries' => 'Top 10 populiarių užklausų:'
        ],
        'pl' => [
            'title' => 'Analizator SEO', 'version' => 'Wersja 1.8', 'slogan' => 'Potężne darmowe narzędzie do analizy i poprawy SEO Twojej strony',
            'h2' => 'Analiza parametrów SEO', 'placeholder' => 'example.com', 'button' => 'Analizuj',
            'error' => 'Błąd: Nie udało się załadować strony. Sprawdź URL i połączenie internetowe.',
            'http_status' => 'Status HTTP: ', 'https_check' => 'HTTPS: ', 'url_structure' => 'Struktura URL: ', 'links_check' => 'Linki: ',
            'social_meta' => 'Open Graph (media społecznościowe): ', 'title_check' => 'Title: ', 'meta_desc' => 'Meta Description: ',
            'meta_keywords' => 'Meta Keywords: ', 'meta_robots' => 'Meta Robots: ', 'h1_check' => 'H1: ', 'h2_check' => 'H2: ',
            'images_alt' => 'Alt przy obrazach: ', 'viewport' => 'Viewport: ', 'load_time' => 'Czas ładowania: ', 'content_size' => 'Rozmiar treści: ',
            'optimal' => 'Doskonałe', 'too_long' => 'Zbyt długi', 'absent' => 'Brak', 'present' => 'Jest', 'too_many' => 'Zbyt wiele',
            'all_with_alt' => 'Wszystkie z alt', 'without_alt' => 'bez alt', 'good' => 'Dobrze', 'slow' => 'Wolno', 'enough' => 'Wystarczająco',
            'low_content' => 'Mało treści', 'noindex' => 'Indeksowanie zabronione', 'not_set' => 'Nie ustawione (indeksowanie dozwolone)',
            'configured' => 'Skonfigurowane', 'secure' => 'Bezpieczne', 'insecure' => 'Niebezpieczne', 'readable' => 'Czytelny',
            'complex' => 'Złożony / długi', 'internal' => 'Wewnętrzne: ', 'external' => 'Zewnętrzne: ', 'nofollow' => 'Nofollow: ',
            'symbols' => 'znak.', 'help' => 'Pomoc', 'about' => 'O programie',
            'about_text' => '<strong>Analizator SEO 1.8</strong> — nowoczesne narzędzie do szybkiej analizy + zamówienie pełnego audytu.',
            'features' => 'Możliwości:', 'features_list' => '<li>Sprawdzenie Title, Description, H1/H2</li><li>Analiza alt obrazów</li><li>Prędkość i rozmiar treści</li><li>Struktura URL i linki</li><li>Open Graph</li><li>8 języków</li><li>Historia ostatnich analiz</li><li>Zamówienie pełnego audytu</li>',
            'howto' => 'Jak korzystać:', 'howto_list' => '<li>Wybierz protokół</li><li>Wpisz domenę</li><li>Kliknij „Analizuj”</li>',
            'tips' => 'Porady SEO (15 przydatnych):',
            'tips_list' => '<li><i class="fas fa-heading"></i> <strong>Title</strong> — 50–60 znaków.</li><li><i class="fas fa-align-left"></i> <strong>Meta Description</strong> — 120–160 znaków z słowami kluczowymi.</li><li><i class="fas fa-font"></i> <strong>H1</strong> — tylko jeden na stronie.</li><li><i class="fas fa-image"></i> <strong>Alt przy obrazach</strong> — obowiązkowe dla wszystkich.</li><li><i class="fas fa-mobile-alt"></i> <strong>Viewport</strong> — wymagany dla wersji mobilnej.</li><li><i class="fas fa-clock"></i> <strong>Czas ładowania</strong> — celuj poniżej 3 sekund.</li><li><i class="fas fa-file-alt"></i> <strong>Treść</strong> — minimum 50 KB tekstu.</li><li><i class="fas fa-link"></i> <strong>URL</strong> — krótki, czytelny, z słowami kluczowymi.</li><li><i class="fas fa-exchange-alt"></i> <strong>Linkowanie wewnętrzne</strong> — rozprowadzaj moc linków.</li><li><i class="fas fa-code"></i> <strong>Schema.org</strong> — bogate snippetki.</li><li><i class="fas fa-link"></i> <strong>Canonical</strong> — unikaj duplikatów.</li><li><i class="fas fa-tachometer-alt"></i> <strong>Core Web Vitals</strong> — LCP < 2.5 s, FID < 100 ms, CLS < 0.1.</li><li><i class="fas fa-file-signature"></i> <strong>Unikalna treść</strong> — nigdy nie kopiuj.</li><li><i class="fas fa-map"></i> <strong>Sitemap.xml</strong> — wyślij do Google i Bing.</li><li><i class="fas fa-key"></i> <strong>Słowa kluczowe</strong> — naturalnie w pierwszym akapicie.</li>',
            'history' => 'Ostatnie analizy', 'scanning' => 'Analizujemy stronę:',
            'order_audit' => 'Zamów pełny audyt', 'donate_title' => 'Wesprzyj projekt',
            'recommendations' => 'Co trzeba naprawić:',
            'rec_title_too_long' => 'Skróć Title do 60 znaków.', 'rec_title_absent' => 'Dodaj tag Title.',
            'rec_meta_desc_too_long' => 'Skróć Description do 160 znaków.', 'rec_meta_desc_absent' => 'Dodaj Meta Description.',
            'rec_h1_absent' => 'Dodaj jeden H1.', 'rec_h1_too_many' => 'Zostaw tylko jeden H1.',
            'rec_images_alt' => 'Dodaj alt do obrazów: ', 'rec_viewport_absent' => 'Dodaj viewport.',
            'rec_load_time_slow' => 'Przyspiesz ładowanie do < 3 sekund.', 'rec_content_low' => 'Zwiększ objętość tekstu do minimum 50 KB.',
            'rec_https_insecure' => 'Przejdź na HTTPS.', 'rec_url_complex' => 'Zrób URL krótszy i czytelniejszy.',
            'rec_social_meta_absent' => 'Dodaj og:title i og:description.',
            'sec' => 'sek.', 'no_history' => 'Brak analiz',
            'name_label' => 'Twoje imię', 'email_label' => 'Email', 'site_label' => 'URL strony',
            'message_label' => 'Co dokładnie przeanalizować', 'submit_audit' => 'Wyślij wniosek',
            'audit_success' => 'Wniosek wysłany pomyślnie! Skontaktujemy się wkrótce.',
            'donate_text' => 'Jeśli narzędzie pomogło — wesprzyj twórcę ☕',
            'coffee_button' => 'Kup mi kawę na BuyMeACoffee',
            'write_dev' => 'Napisz do twórcy',
            'popularity' => 'Popularność zapytań wyszukiwania',
            'queries_count' => 'Liczba zapytań: ',
            'top_10_queries' => 'Top 10 popularnych zapytań:'
        ],
        'ge' => [
            'title' => 'SEO ანალიზატორი', 'version' => 'ვერსია 1.8', 'slogan' => 'ძლიერი უფასო ინსტრუმენტი თქვენი საიტის SEO ანალიზისა და გაუმჯობესებისთვის',
            'h2' => 'SEO პარამეტრების ანალიზი', 'placeholder' => 'example.com', 'button' => 'ანალიზი',
            'error' => 'შეცდომა: ვერ მოხერხდა გვერდის ჩატვირთვა. შეამოწმეთ URL და ინტერნეტი.',
            'http_status' => 'HTTP სტატუსი: ', 'https_check' => 'HTTPS: ', 'url_structure' => 'URL სტრუქტურა: ', 'links_check' => 'ბმულები: ',
            'social_meta' => 'Open Graph (სოციალური ქსელები): ', 'title_check' => 'Title: ', 'meta_desc' => 'Meta Description: ',
            'meta_keywords' => 'Meta Keywords: ', 'meta_robots' => 'Meta Robots: ', 'h1_check' => 'H1: ', 'h2_check' => 'H2: ',
            'images_alt' => 'Alt სურათებზე: ', 'viewport' => 'Viewport: ', 'load_time' => 'ჩატვირთვის დრო: ', 'content_size' => 'კონტენტის ზომა: ',
            'optimal' => 'შესანიშნავი', 'too_long' => 'ძალიან გრძელი', 'absent' => 'არ არის', 'present' => 'არის', 'too_many' => 'ძალიან ბევრი',
            'all_with_alt' => 'ყველა alt-ით', 'without_alt' => 'alt-ის გარეშე', 'good' => 'კარგი', 'slow' => 'ნელი', 'enough' => 'საკმარისი',
            'low_content' => 'მცირე კონტენტი', 'noindex' => 'ინდექსაცია აკრძალულია', 'not_set' => 'არ არის მითითებული (ინდექსაცია დაშვებულია)',
            'configured' => 'კონფიგურირებული', 'secure' => 'უსაფრთხო', 'insecure' => 'არა უსაფრთხო', 'readable' => 'წაკითხვადი',
            'complex' => 'რთული / გრძელი', 'internal' => 'შიდა: ', 'external' => 'გარე: ', 'nofollow' => 'Nofollow: ',
            'symbols' => 'სიმბ.', 'help' => 'დახმარება', 'about' => 'პროგრამის შესახებ',
            'about_text' => '<strong>SEO ანალიზატორი 1.8</strong> — თანამედროვე ინსტრუმენტი სწრაფი ანალიზისთვის + სრული აუდიტის შეკვეთა.',
            'features' => 'შესაძლებლობები:', 'features_list' => '<li>Title, Description, H1/H2 შემოწმება</li><li>სურათების alt ანალიზი</li><li>ჩატვირთვის სიჩქარე და კონტენტის ზომა</li><li>URL სტრუქტურა და ბმულები</li><li>Open Graph</li><li>8 ენა</li><li>ბოლო ანალიზების ლენტა</li><li>სრული აუდიტის შეკვეთა</li>',
            'howto' => 'როგორ გამოვიყენოთ:', 'howto_list' => '<li>აირჩიეთ პროტოკოლი</li><li>შეიყვანეთ დომენი</li><li>დააჭირეთ „ანალიზი“</li>',
            'tips' => 'SEO ოპტიმიზაციის რჩევები (15 სასარგებლო):',
            'tips_list' => '<li><i class="fas fa-heading"></i> <strong>Title</strong> — 50–60 სიმბოლო.</li><li><i class="fas fa-align-left"></i> <strong>Meta Description</strong> — 120–160 სიმბოლო საკვანძო სიტყვებით.</li><li><i class="fas fa-font"></i> <strong>H1</strong> — მხოლოდ ერთი გვერდზე.</li><li><i class="fas fa-image"></i> <strong>Alt სურათებზე</strong> — სავალდებულო ყველასთვის.</li><li><i class="fas fa-mobile-alt"></i> <strong>Viewport</strong> — სავალდებულო მობილურისთვის.</li><li><i class="fas fa-clock"></i> <strong>ჩატვირთვის სიჩქარე</strong> — მიზანი 3 წამზე ნაკლები.</li><li><i class="fas fa-file-alt"></i> <strong>კონტენტი</strong> — მინიმუმ 50 KB ტექსტი.</li><li><i class="fas fa-link"></i> <strong>URL</strong> — მოკლე, წაკითხვადი, საკვანძო სიტყვებით.</li><li><i class="fas fa-exchange-alt"></i> <strong>შიდა ლინკინგი</strong> — განაწილეთ წონა.</li><li><i class="fas fa-code"></i> <strong>Schema.org</strong> — მდიდარი სნიპეტები.</li><li><i class="fas fa-link"></i> <strong>Canonical</strong> — თავიდან აიცილეთ დუბლიკატები.</li><li><i class="fas fa-tachometer-alt"></i> <strong>Core Web Vitals</strong> — LCP < 2.5 წმ, FID < 100 მწმ, CLS < 0.1.</li><li><i class="fas fa-file-signature"></i> <strong>უნიკალური კონტენტი</strong> — არასოდეს დააკოპიროთ.</li><li><i class="fas fa-map"></i> <strong>Sitemap.xml</strong> — გაგზავნეთ Google-სა და Yandex-ში.</li><li><i class="fas fa-key"></i> <strong>საკვანძო სიტყვები</strong> — ბუნებრივად პირველ აბზაცში.</li>',
            'history' => 'ბოლო ანალიზები', 'scanning' => 'ანალიზდება საიტი:',
            'order_audit' => 'სრული აუდიტის შეკვეთა', 'donate_title' => 'პროექტის მხარდაჭერა',
            'recommendations' => 'რა უნდა გამოსწორდეს:',
            'rec_title_too_long' => 'შეამცირეთ Title 60 სიმბოლომდე.', 'rec_title_absent' => 'დაამატეთ Title ტეგი.',
            'rec_meta_desc_too_long' => 'შეამცირეთ Description 160 სიმბოლომდე.', 'rec_meta_desc_absent' => 'დაამატეთ Meta Description.',
            'rec_h1_absent' => 'დაამატეთ ერთი H1.', 'rec_h1_too_many' => 'დატოვეთ მხოლოდ ერთი H1.',
            'rec_images_alt' => 'დაამატეთ alt სურათებს: ', 'rec_viewport_absent' => 'დაამატეთ viewport.',
            'rec_load_time_slow' => 'დააჩქარეთ ჩატვირთვა < 3 წამამდე.', 'rec_content_low' => 'გაზარდეთ ტექსტის მოცულობა მინიმუმ 50 KB-მდე.',
            'rec_https_insecure' => 'გადადით HTTPS-ზე.', 'rec_url_complex' => 'გახადეთ URL უფრო მოკლე და წაკითხვადი.',
            'rec_social_meta_absent' => 'დაამატეთ og:title და og:description.',
            'sec' => 'წმ.', 'no_history' => 'ანალიზები ჯერ არ არის',
            'name_label' => 'თქვენი სახელი', 'email_label' => 'Email', 'site_label' => 'საიტის URL',
            'message_label' => 'რა ზუსტად უნდა გაანალიზოთ', 'submit_audit' => 'გაგზავნეთ მოთხოვნა',
            'audit_success' => 'მოთხოვნა წარმატებით გაიგზავნა! დაგიკავშირდებით მალე.',
            'donate_text' => 'თუ ინსტრუმენტი დაგეხმარათ — დაუჭირეთ მხარი შემქმნელს ☕',
            'coffee_button' => 'იყიდე ყავა BuyMeACoffee-ზე',
            'write_dev' => 'დაწერე შემქმნელს',
            'popularity' => 'ძიების მოთხოვნების პოპულარობა',
            'queries_count' => 'მოთხოვნების რაოდენობა: ',
            'top_10_queries' => 'Top-10 პოპულარული მოთხოვნები:'
        ],
        'no' => [
            'title' => 'SEO Analyzer', 'version' => 'Versjon 1.8', 'slogan' => 'Kraftig gratis verktøy for analyse og forbedring av SEO på nettstedet ditt',
            'h2' => 'SEO-parametere analyse', 'placeholder' => 'example.com', 'button' => 'Analyser',
            'error' => 'Feil: Kunne ikke laste siden. Sjekk URL og internettforbindelse.',
            'http_status' => 'HTTP-status: ', 'https_check' => 'HTTPS: ', 'url_structure' => 'URL-struktur: ', 'links_check' => 'Lenker: ',
            'social_meta' => 'Open Graph (sosiale medier): ', 'title_check' => 'Title: ', 'meta_desc' => 'Meta Description: ',
            'meta_keywords' => 'Meta Keywords: ', 'meta_robots' => 'Meta Robots: ', 'h1_check' => 'H1: ', 'h2_check' => 'H2: ',
            'images_alt' => 'Alt på bilder: ', 'viewport' => 'Viewport: ', 'load_time' => 'Lastetid: ', 'content_size' => 'Innholdsstørrelse: ',
            'optimal' => 'Utmerket', 'too_long' => 'For lang', 'absent' => 'Mangler', 'present' => 'Finnes', 'too_many' => 'For mange',
            'all_with_alt' => 'Alle med alt', 'without_alt' => 'uten alt', 'good' => 'Bra', 'slow' => 'Langsom', 'enough' => 'Tilstrekkelig',
            'low_content' => 'Lite innhold', 'noindex' => 'Indeksering forbudt', 'not_set' => 'Ikke satt (indeksering tillatt)',
            'configured' => 'Konfigurert', 'secure' => 'Sikkert', 'insecure' => 'Usikkert', 'readable' => 'Lesbart',
            'complex' => 'Komplekst / langt', 'internal' => 'Interne: ', 'external' => 'Eksterne: ', 'nofollow' => 'Nofollow: ',
            'symbols' => 'tegn', 'help' => 'Hjelp', 'about' => 'Om programmet',
            'about_text' => '<strong>SEO Analyzer 1.8</strong> — moderne verktøy for rask analyse + bestilling av full audit.',
            'features' => 'Funksjoner:', 'features_list' => '<li>Sjekk av Title, Description, H1/H2</li><li>Alt-analyse på bilder</li><li>Lastetid og innholdsstørrelse</li><li>URL-struktur og lenker</li><li>Open Graph</li><li>8 språk</li><li>Historikk over siste analyser</li><li>Bestilling av full audit</li>',
            'howto' => 'Slik bruker du:', 'howto_list' => '<li>Velg protokoll</li><li>Skriv inn domene</li><li>Klikk „Analyser“</li>',
            'tips' => 'SEO-optimaliseringstips (15 nyttige):',
            'tips_list' => '<li><i class="fas fa-heading"></i> <strong>Title</strong> — 50–60 tegn.</li><li><i class="fas fa-align-left"></i> <strong>Meta Description</strong> — 120–160 tegn med nøkkelord.</li><li><i class="fas fa-font"></i> <strong>H1</strong> — kun én per side.</li><li><i class="fas fa-image"></i> <strong>Alt på bilder</strong> — obligatorisk for alle.</li><li><i class="fas fa-mobile-alt"></i> <strong>Viewport</strong> — nødvendig for mobil.</li><li><i class="fas fa-clock"></i> <strong>Lastetid</strong> — mål under 3 sekunder.</li><li><i class="fas fa-file-alt"></i> <strong>Innhold</strong> — minst 50 KB tekst.</li><li><i class="fas fa-link"></i> <strong>URL</strong> — kort, lesbart, med nøkkelord.</li><li><i class="fas fa-exchange-alt"></i> <strong>Intern lenking</strong> — fordel linkkraft.</li><li><i class="fas fa-code"></i> <strong>Schema.org</strong> — rike snippets.</li><li><i class="fas fa-link"></i> <strong>Canonical</strong> — unngå duplikater.</li><li><i class="fas fa-tachometer-alt"></i> <strong>Core Web Vitals</strong> — LCP < 2.5 s, FID < 100 ms, CLS < 0.1.</li><li><i class="fas fa-file-signature"></i> <strong>Unikt innhold</strong> — aldri kopier.</li><li><i class="fas fa-map"></i> <strong>Sitemap.xml</strong> — send til Google og Bing.</li><li><i class="fas fa-key"></i> <strong>Nøkkelord</strong> — naturlig i første avsnitt.</li>',
            'history' => 'Siste analyser', 'scanning' => 'Analyserer nettsted:',
            'order_audit' => 'Bestill full audit', 'donate_title' => 'Støtt prosjektet',
            'recommendations' => 'Hva må fikses:',
            'rec_title_too_long' => 'Forkort Title til 60 tegn.', 'rec_title_absent' => 'Legg til Title-tag.',
            'rec_meta_desc_too_long' => 'Forkort Description til 160 tegn.', 'rec_meta_desc_absent' => 'Legg til Meta Description.',
            'rec_h1_absent' => 'Legg til én H1.', 'rec_h1_too_many' => 'Behold kun én H1.',
            'rec_images_alt' => 'Legg til alt på bilder: ', 'rec_viewport_absent' => 'Legg til viewport.',
            'rec_load_time_slow' => 'Øk hastigheten til < 3 sekunder.', 'rec_content_low' => 'Øk tekstvolum til minst 50 KB.',
            'rec_https_insecure' => 'Bytt til HTTPS.', 'rec_url_complex' => 'Gjør URL kortere og lesbar.',
            'rec_social_meta_absent' => 'Legg til og:title og og:description.',
            'sec' => 'sek.', 'no_history' => 'Ingen analyser ennå',
            'name_label' => 'Ditt navn', 'email_label' => 'E-post', 'site_label' => 'Nettsted-URL',
            'message_label' => 'Hva skal analyseres', 'submit_audit' => 'Send forespørsel',
            'audit_success' => 'Forespørsel sendt! Vi kontakter deg snart.',
            'donate_text' => 'Hvis verktøyet hjalp — støtt utvikleren ☕',
            'coffee_button' => 'Kjøp kaffe til meg på BuyMeACoffee',
            'write_dev' => 'Skriv til utvikleren',
            'popularity' => 'Popularitet for søkefraser',
            'queries_count' => 'Antall søk: ',
            'top_10_queries' => 'Topp 10 populære søk:'
        ]
    ];

    $t = $translations[$lang] ?? $translations['ru'];
    foreach ($translations['ru'] as $k => $v) {
        if (!isset($t[$k])) $t[$k] = $v;
    }
    return $t;
}
?>